### ISSUE TITLE
Error: EACCES: permission denied, stat '/root/.bashrc'

### ISSUE THREAD

**Issue by habibieeddien** [Rainbow-CPaaS/Rainbow-CLI-SDK#2]
I have struggle to install with `sudo npm install -g rainbow-cli`

![image](https://user-images.githubusercontent.com/14885631/44950920-d5738f00-ae7f-11e8-9c21-00cc31fd3ecc.png)

This is permission status of `/root/.bashrc`

![image](https://user-images.githubusercontent.com/14885631/44950940-3dc27080-ae80-11e8-8988-da99cfb3c97f.png)

Please help me to install this on my VPS Ubuntu 16.
I was successfully installed on my Windows 10 locally.

**Comment by zucher** [comment]
Hi @habibieeddien,

As root user, you don't need to use "sudo" command be "npm -g".

Could you try ?

Regards

Vincent

**Comment by habibieeddien** [comment]
Hi @zucher 

It's same result. But I got my self solution. I just install local in path here `/usr/lib/node_modules`

and execute `npm i rainbow-cli`

Thanks for your response.

**Comment by zucher** [comment]
An other solution is to use a dedicated local npm_package directory declared into .npmrc. And add the $npm_package/bin path in the user .bashrc PATH variable.
