### ISSUE TITLE
TypeError: Cannot set property 'details' of undefined

### ISSUE THREAD

**Issue by MahmoudAbdAlKareem** [Rainbow-CPaaS/Rainbow-CLI-SDK#3]
rbw login command is not working, after I try to output the command it shows the following error: 
TypeError: Cannot set property 'details' of undefined. 

![image](https://user-images.githubusercontent.com/16404421/57191450-84e09400-6f2e-11e9-9819-ab17837145fd.png)

**Comment by Fab06460** [comment]
Hi Mahmoud,

Please verify your rbw configure parameters (seems they are not ok and you cannot login).
The TypeError exception is corrected in rainbow-cli 1.56.2 (was happening when rbw login failed).

BR
fabrice.
