### ISSUE TITLE
Can't create New Test account by command

### ISSUE THREAD

**Issue by han814992037** [Rainbow-CPaaS/Rainbow-CLI-SDK#4]
when I use rbw create user command
 
>rbw create user 'atestuser@acompany.com' 'aPassword_123' 'aFirstname' 'aLastnameasadasd'
It will show error : missing required argument `lastname'
but If I use 
rbw create user 'atestuser@acompany.com' 'afullname' 'aPassword_123' 'aFirstname' 'aLastnameasadasd'
It will show error :Invalid command. Type option --help to get the list of available options

**Comment by Fab06460** [comment]
Hi,

The issue has been fixed in rainbow-cli 1.56.1.

BR
fabrice.

**Comment by han814992037** [comment]
OK,thanks very much
