### ISSUE TITLE
Can't use Oauth function

### ISSUE THREAD

**Issue by han814992037** [Rainbow-CPaaS/Rainbow-CLI-SDK#5]
![T3}7}K )LR@}3 Q$XXH`7ZE](https://user-images.githubusercontent.com/19885368/60008288-697c4480-96a6-11e9-8363-7617c13b4f70.png)

**Comment by zucher** [comment]
Hi,

did you set the authorization URL as: https://openrainbow.com/api/rainbow/authentication/v1.0/oauth/authorize ?

Regards

zucher

**Comment by han814992037** [comment]
OK, If I remove 'www', It's work fine!
Thanks very much.
Xu
